// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WantedRobots.Models;

#nullable disable

namespace WantedRobots.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230925134556_AddAgentRelationshipToRobot")]
    partial class AddAgentRelationshipToRobot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WantedRobots.Models.AgentRobot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Commentaire")
                        .HasColumnType("longtext");

                    b.Property<string>("Continent")
                        .HasColumnType("longtext");

                    b.Property<double>("Identification")
                        .HasColumnType("double");

                    b.Property<string>("NomAgent")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AgentRobots");
                });

            modelBuilder.Entity("WantedRobots.Models.DeletedRobot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .HasColumnType("longtext");

                    b.Property<string>("Pays")
                        .HasColumnType("longtext");

                    b.Property<double>("Poids")
                        .HasColumnType("double");

                    b.Property<double>("Taille")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("DeletedRobots");
                });

            modelBuilder.Entity("WantedRobots.Models.Robot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AgentId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Poids")
                        .HasColumnType("double");

                    b.Property<double>("Taille")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("Robots", (string)null);
                });

            modelBuilder.Entity("WantedRobots.Models.Robot", b =>
                {
                    b.HasOne("WantedRobots.Models.AgentRobot", "Agent")
                        .WithMany("Robots")
                        .HasForeignKey("AgentId");

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("WantedRobots.Models.AgentRobot", b =>
                {
                    b.Navigation("Robots");
                });
#pragma warning restore 612, 618
        }
    }
}
